# OpenAI Codex CLI Configuration for CloudBase AI ToolKit
# This configuration enables MCP (Model Context Protocol) support for CloudBase tools
model_provider = "codex"
model = "gpt-5-codex"
model_reasoning_effort = "high"
disable_response_storage = true
windows_wsl_setup_acknowledged = true


[model_providers.codex]
name = "codex"
base_url = "https://code.ppchat.vip/v1"
wire_api = "responses"
requires_openai_auth = true

[projects.'C:\Users\31328']
trust_level = "trusted"

[projects.'D:\gsxm\xingjuai.icu']
trust_level = "trusted"

[projects.'\\?\D:\gsxm\timao-douyin-live-manager']
trust_level = "trusted"

[mcp_servers.cloudbase]
command = "npx"
args = ["npm-global-exec@latest", "@cloudbase/cloudbase-mcp@latest"]
env = { INTEGRATION_IDE = "CodeX" }