version: '3.8'

services:
  timao-live-manager:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: timao-douyin-live-manager
    image: timao-live-manager:latest
    ports:
      - "30013:30013"  # Vite 前端
      - "{PORT}:{PORT}"  # FastAPI 后端（默认端口为 9019，可通过环境变量 BACKEND_PORT 修改）
      - "5000:5000"    # Flask 服务
    environment:
      - NODE_ENV=development
      - PYTHONUNBUFFERED=1
      # 可以添加其他环境变量，例如：
      # - OPENAI_API_KEY=${OPENAI_API_KEY}
      # - DASHSCOPE_API_KEY=${DASHSCOPE_API_KEY}
    volumes:
      # 挂载代码目录（开发模式下实时同步）
      - .:/app
      # 排除 node_modules（使用容器内的）
      - /app/node_modules
      - /app/electron/renderer/node_modules
    restart: unless-stopped
    networks:
      - timao-network
    # 如果需要访问音频设备（仅 Linux 支持）
    # devices:
    #   - /dev/snd:/dev/snd
    # privileged: true

networks:
  timao-network:
    driver: bridge
