#!/bin/bash
# 提猫直播助手 - 常用命令快捷方式

echo "================================================"
echo "  提猫直播助手 - 常用命令"
echo "================================================"
echo ""
echo "1. 前端部署"
echo "   ./scripts/快速部署.sh"
echo ""
echo "2. 查看后端日志"
echo "   pm2 logs timao-backend"
echo ""
echo "3. 重启后端服务"
echo "   pm2 restart timao-backend"
echo ""
echo "4. 重启所有服务"
echo "   pm2 restart all"
echo ""
echo "5. 查看服务状态"
echo "   pm2 list"
echo ""
echo "6. 查看构建日志"
echo "   tail -f build-deploy.log"
echo ""
echo "7. 测试公网访问"
echo "   curl http://129.211.218.135/health"
echo ""
echo "8. 查看备份列表"
echo "   ls -lt /www/wwwroot/timao-app-backups/"
echo ""
echo "9. 重新加载 Nginx"
echo "   nginx -s reload"
echo ""
echo "10. 查看 Nginx 日志"
echo "    tail -f /www/wwwlogs/timao-error.log"
echo ""
echo "================================================"
